### ISSUE TITLE
no config file generated

### ISSUE THREAD

**Issue by EnderMelody** [Emafire003/ColoredGlowLib#12]
minecraft: 1.20.1
quilt: 0.20.2  (tried with fabric as well)
colorglow lib: 2.1.0-fabric_1.20.1

not sure if im missing something but there doesnt seem to be any config for the mod anywhere, and you cant open the config from mod menu either. i tried changing the settings in game using commands but there was still no config generated, and i dont see a way to apply global settings per mob type (or it at least didnt apply globally).

**Comment by EnderMelody** [comment]
just happened to look at the logs while testing something and im getting this error spammed 
"[14:50:33] [Server thread/INFO]: Saving ConfigDataSaver...
[14:50:33] [Server thread/INFO]: [STDERR]: java.nio.file.NoSuchFileException: C:\Users\Ender\Desktop\Games\MINEcraft\MultiMC\instances\1.20.1 Quilt\.minecraft\config\coloredglowlib\coloredglowlib_config.json"

so it is definitely something wrong with the config saving/creating

**Comment by Emafire003** [comment]
Looking into it

**Comment by Emafire003** [comment]
Solved!
