### ISSUE TITLE
setglowcolor doesnt accept entity type

### ISSUE THREAD

**Issue by EnderMelody** [Emafire003/ColoredGlowLib#13]
minecraft: 1,20.1
quilt: 0.20.2
cgl: 2.1.1+fabric_1.20.1

using the setglowcolor command and trying to apply it to an entity type gives an error on the entity specification:
"expected whitespace to end one argument, but found trailing data at position 27: ... minecraft<--[HERE]". 

using a specific entity works fine such as @e[type=horse] but it doesnt apply to all entities that were not in the area of effect, and it is not saved on reloading the world.

**Comment by Emafire003** [comment]
Fixed, apparently between 1.19 and  1.20 the command decided it did not want to accept entitytypes in the same way. (The other bug is fixed as well, uploading the new version now)

**Comment by EnderMelody** [comment]
new version now crashes when loading into a world.
[crash-2023-09-06_11.25.41-server.txt](https://github.com/Emafire003/ColoredGlowLib/files/12539614/crash-2023-09-06_11.25.41-server.txt)

cant seem to reopen the issue so ill just make a new one
