### ISSUE TITLE
crash when opening a world

### ISSUE THREAD

**Issue by EnderMelody** [Emafire003/ColoredGlowLib#14]
minecraft: 1.20.1
quilt: 0.20.2 (tested with fabric)
cgl: 2.2.0+fabric_1.20.1
hard crash when loading into any world with the mod installed.
[crash-2023-09-06_11.25.41-server.txt](https://github.com/Emafire003/ColoredGlowLib/files/12539614/crash-2023-09-06_11.25.41-server.txt)

**Comment by EnderMelody** [comment]
also, the required mods isnt working so launching without them hard crashes the game instead of opening the fabric incompatible mod menu.

**Comment by Emafire003** [comment]
There is no compatibility with mod menu, sorry and I can't guarantee it will ever have one. As for the crash, for some reason sometimes after updating the dependecies on 1.20.2 it crashes. Didn't even notice it, thanks.

**Comment by EnderMelody** [comment]
no problem, sorry for having you fix all these problems and thanks for making these cool mods! 
as for the mod menu comparability, did you mean that has anything to do with the crashes or did you mean to reply to another issue? as long as it can run without crashing its no problem.

**Comment by Emafire003** [comment]
No it doesn't have anything to do with the crashes. Btw, the new version is up on modrinth, let me know if you find any other problems

**Comment by EnderMelody** [comment]
now crashes when trying to load the game with an edited config for colorglowlib.
loading the game the first time with cgl runs fine, you can load the world and set colors for specific entites and it saves to the config fine. however once you close the game and try to launch it again it hard crashes.
[crash-2023-09-07_14.25.49-client.txt](https://github.com/Emafire003/ColoredGlowLib/files/12552358/crash-2023-09-07_14.25.49-client.txt)
deleting the config allows the game to load properly again.

**Comment by Emafire003** [comment]
I hate GSON. It didn't like the enitytype format, uploading a new release now. Hopefully, it's the last fix I need to make ahah

**Comment by EnderMelody** [comment]
yup, everything seems to work perfectly now, thanks for all the updates!
