### ISSUE TITLE
A query

### ISSUE THREAD

**Issue by Onionbhai** [Emafire003/ColoredGlowLib#17]
Bro I have used the mod I very amazing but I just want to know that how's the acacia biome colour blue and the structure of the trees different is there any plugin for the terrain and trees and also tell the texture pack name to make the colour of acacia grass blue
And also I am saying this again that this mod is very amazing so please tell the texture pack and plugin name

**Comment by Emafire003** [comment]
What?

**Comment by Emafire003** [comment]
Ahhhh. It's just Terralith and one of their biomes, can't remember the name. If you were talking about the screenshots. Anyway, thank you for the compliments I guess?
