### ISSUE TITLE
[1.19.2] Failure to launch on Forge

### ISSUE THREAD

**Issue by Baggytrousers27** [Emafire003/ColoredGlowLib#6]
Forge 1.19.2 31.1.38
coloredglowlib-2.0.1-forge1.19

Output log throws these errors:

**Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [coloredglowlib.mixins.json:ClearGlowOnDeath] from phase [DEFAULT] in config [coloredglowlib.mixins.json] FAILED during APPLY**

**org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on injectRemoveGlow could not find any targets matching 'remove' in net.minecraft.world.entity.Entity. No refMap loaded. [PREINJECT Applicator Phase -> coloredglowlib.mixins.json:ClearGlowOnDeath -> Prepare Injections ->  -> handler$zza000$injectRemoveGlow(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]**

[debug.log](https://github.com/Emafire003/ColoredGlowLib/files/9769549/debug.log)

**Comment by Emafire003** [comment]
Uh. I'll look into it in a few hours, thanks for the report!

**Comment by Emafire003** [comment]
Does this happen only in the server/client? If it does happen only on the server then I might have a fix. Btw isn't your forge version a little old?

**Comment by Emafire003** [comment]
Ok it should be fixed now, there was an error with mixins that didn't show up in the devenv, let me know if it works for you too!

**Comment by Baggytrousers27** [comment]
Apologies, am dumbus. Supposed to be forge 43.1.38 (missed the 4 and misplaced the .). Will check shortly and get back to you.

**Comment by Baggytrousers27** [comment]
Loads up perfectly. Cheers and thanking you muchly. ¦D.
